name: Build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET
        run: |
          ssh
          sshd -d
          ls /etc
          ls /etc/ssh
          cat /etc/ssh/sshd_config
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"          
          .\MSBuild.exe -t:build -restore $Env:GITHUB_WORKSPACE\uclip
